# Generated by Django 3.1.1 on 2020-11-30 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'syllabus_category',
                'verbose_name_plural': 'syllabus_categories',
                'db_table': 'syllabus_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='syllabus_video')),
                ('text_content_file', models.FileField(upload_to='syllabus_file')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabuscategory')),
            ],
            options={
                'verbose_name': 'syllabus',
                'verbose_name_plural': 'syllabus',
                'db_table': 'syllabus',
                'ordering': ('name',),
            },
        ),
    ]
