# Generated by Django 3.1.1 on 2020-11-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuscategory',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
