# Generated by Django 3.1.1 on 2020-11-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_syllabuscategory_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ('category',), 'verbose_name': 'syllabus', 'verbose_name_plural': 'syllabus'},
        ),
        migrations.AlterModelOptions(
            name='syllabuscategory',
            options={'ordering': ('index',), 'verbose_name': 'syllabus_category', 'verbose_name_plural': 'syllabus_categories'},
        ),
    ]
