# Generated by Django 3.1.1 on 2020-11-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20201130_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuscategory',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
