# Generated by Django 3.1.1 on 2020-11-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20201130_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuscategory',
            name='slug',
            field=models.SlugField(max_length=251),
        ),
    ]
