# Generated by Django 3.1.1 on 2020-11-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0007_auto_20201130_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabuscategory',
            name='slug',
        ),
    ]
