# Generated by Django 3.1.1 on 2020-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0008_remove_syllabuscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabuscategory',
            name='slug',
            field=models.SlugField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
