# Generated by Django 3.1.1 on 2020-11-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0009_syllabuscategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabuscategory',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
