# Generated by Django 3.1.1 on 2020-12-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0011_auto_20201220_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='subCategory',
        ),
    ]
