# Generated by Django 3.1.1 on 2020-12-20 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0012_remove_syllabus_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='subCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabussubcategory'),
            preserve_default=False,
        ),
    ]
