# Generated by Django 3.1.1 on 2021-06-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0013_syllabus_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'syllabus_type',
                'verbose_name_plural': 'syllabus_types',
                'db_table': 'syllabus_type',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='text_content_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_file'),
        ),
    ]
