# Generated by Django 3.1.1 on 2021-06-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0015_auto_20210619_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabusType',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabustypeName',
        ),
    ]
