# Generated by Django 3.1.1 on 2021-06-19 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0016_auto_20210619_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='syllabusType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabustype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabustypeName',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
