# Generated by Django 3.1.1 on 2021-06-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0017_auto_20210619_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='subCategory',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='syllabusType',
            new_name='syllabus_type',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='syllabustypeName',
            new_name='syllabus_type_name',
        ),
    ]
