# Generated by Django 3.1.1 on 2021-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0018_auto_20210619_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='syllabus_video'),
        ),
    ]
