# Generated by Django 3.1.1 on 2021-06-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0019_auto_20210619_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_type_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
