# Generated by Django 3.1.1 on 2021-06-22 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0020_auto_20210619_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabustype'),
        ),
    ]
