# Generated by Django 3.1.1 on 2021-06-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0021_auto_20210622_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_type',
        ),
    ]
