# Generated by Django 3.1.1 on 2021-06-24 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0023_syllabus_syllabus_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_type_name',
        ),
    ]
