# Generated by Django 3.1.1 on 2021-06-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0024_remove_syllabus_syllabus_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_type',
        ),
    ]
