# Generated by Django 3.1.1 on 2021-06-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0025_remove_syllabus_syllabus_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_type',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabustype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_type_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
