# Generated by Django 3.1.1 on 2021-06-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0026_auto_20210624_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='syllabus_type',
            new_name='syllabusType',
        ),
    ]
