# Generated by Django 3.1.1 on 2021-06-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0028_auto_20210624_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabustype'),
        ),
    ]
