# Generated by Django 3.1.1 on 2021-06-24 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0029_auto_20210624_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_type_name',
        ),
    ]
