# Generated by Django 3.1.1 on 2020-09-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questioncategory',
            table='question_category',
        ),
    ]
