# Generated by Django 3.1.1 on 2020-09-28 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20200928_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'ordering': ('name',), 'verbose_name': 'question_category', 'verbose_name_plural': 'question_categories'},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='question_video')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.questioncategory')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
                'ordering': ('name',),
            },
        ),
    ]
