# Generated by Django 3.1.1 on 2020-09-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
    ]
