# Generated by Django 3.1.1 on 2020-10-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_auto_20200928_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(default=None, upload_to='question_file'),
            preserve_default=False,
        ),
    ]
