# Generated by Django 3.1.1 on 2020-10-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_question_question_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestoinDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'question_difficulty',
                'verbose_name_plural': 'question_difficulties',
                'db_table': 'question_difficulty',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.questoindifficulty'),
            preserve_default=False,
        ),
    ]
