# Generated by Django 3.1.1 on 2021-06-26 08:24

import compiler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorial', '0030_remove_syllabus_syllabus_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_created=True)),
                ('is_correct_answer', models.BooleanField(default=False)),
                ('code_file', models.FileField(upload_to=compiler.models.getUploadPath)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabus')),
            ],
        ),
    ]
