# Generated by Django 3.1.1 on 2021-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_usercode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='status',
            field=models.CharField(default='Correct', max_length=250),
            preserve_default=False,
        ),
    ]
