# Generated by Django 3.1.1 on 2021-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_usercode_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='createdAt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
