# Generated by Django 3.1.1 on 2021-06-27 15:44

import compiler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0030_remove_syllabus_syllabus_type_name'),
        ('compiler', '0005_testinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinput',
            name='file',
            field=models.FileField(upload_to=compiler.models.getTestInputFilePath),
        ),
        migrations.CreateModel(
            name='TestOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=compiler.models.getTestOutputFilePath)),
                ('time_limit', models.IntegerField()),
                ('Syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.syllabus')),
            ],
        ),
    ]
