# Generated by Django 3.1.1 on 2021-06-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_auto_20210627_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testinput',
            old_name='Syllabus',
            new_name='syllabus',
        ),
        migrations.RenameField(
            model_name='testoutput',
            old_name='Syllabus',
            new_name='syllabus',
        ),
    ]
