# Generated by Django 3.1.1 on 2020-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200925_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='txn_response_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
